### PR TITLE
feat: demo tests of user variables

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

This demonstrates how we can store a reference to the user's global variables and their code.  I added a basic test and a tiny notebook for testing purposes.

The easiest way to test locally is simply to open the notebook in VSCode and run the cell.

### CODE REVIEW

**Comment by sidemt** [comment]
@ojeytonwilliams Is it expected to give False here since it's set to "some text"?
image

**Comment by sidemt** [comment]
@ojeytonwilliams Is it expected to give False here since it's set to "some text"?
image

**Comment by ojeytonwilliams** [comment]
> @ojeytonwilliams Is it expected to give False here since it's set to "some text"? 

It is, yes.  If you edit `var = "some text"` to be `var = "demo"` then it will give the following output:

```
User's "var" variable is set to "demo"?
True
User's code
import tests; tests.prepare(globals(), In)

var = "demo"

tests.step01()
```

The ideas is just to demonstrate that you can pass in `globals()` to your tests and then they have full access to everything the user has created in the notebook.  Assuming I understand `globals` correctly!

**Review by sidemt — APPROVED** [review]
@ojeytonwilliams Thank you for confirming. Then LGTM!

**Review by ShaunSHamilton — APPROVED** [review]
Seems like a fun start to me 👍

**Pull request merged**
